#
# OCR4all app
# Application Properties
#
# Author:   Herbert Baier (herbert.baier@uni-wuerzburg.de)
# Date:     03.11.2020
#

#
# spring configuration
#
spring:
  profiles:
    active:
      - logging-debug
      - server
      - api
      - documentation
      - development
  servlet.multipart:
    max-file-size: 256MB
    max-request-size: 2GB
    enabled: true
    location: ${java.io.tmpdir}
    
#
# server configuration
#
server:
  port: 8080

#
# context path
#
#server.servlet.context-path: /path

#
# open API documentation
#
# sort: 
#   tags-sorter -> sorts tags (e.g. controllers)
#   operations-sorter -> sorts methods
springdoc:
  packagesToScan: de.uniwuerzburg.zpd.ocr4all.application.api
  pathsToMatch: /api/**
  api-docs.path: /api/doc
  swagger-ui:
    path: /api/doc/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

#
# ocr4all configuration
#
ocr4all:
  application:
    label: ocr4all-app
    name: ocr4all app
    charset: UTF_8
    date.format: yyyy-MM-dd HH:mm:ss
    locale:
      language: en
      region: US
    view.languages:
      - en
      - de
    monitor.interval: 15000
    thread.pool.size: 
      task: 6
      workflow: 12
    spi.msa:
      - id: ocrd
        url: localhost:9091
        websocket:
          end-point: /event
          topic: /topic/spi
          resilience:
            max-attempts: 3
            delay-between-attempts: 1000
            wait-duration: 15000
    security:
      groups:
        administrator: admin
        coordinator: coord
      administrator:
        create: false
        login: admin
        password: ocr4all
  system:
    unix:
      command:
        docker: /usr/bin/docker
        convert: /usr/bin/convert
        identify: /usr/bin/identify
    mac:
      command:
        docker: /usr/local/bin/docker
        convert: /opt/local/bin/convert
        identify: /opt/local/bin/identify
    windows:
      command:
        docker: C:/Program Files/Docker/docker.exe
        convert: C:/Program Files/ImageMagick-7.1.0/convert
        identify: C:/Program Files/ImageMagick-7.1.0/identify
  image.derivatives:
    best:
      quality: 50
      max-size: 1536x1536
    detail:
      quality: 50
      max-size: 768x768
    thumbnail:
      quality: 50
      max-size: 128x128
  exchange.folder: ${user.home}/ocr4all/exchange
  repository:
    folder: ${user.home}/ocr4all/repository
    configuration:
      folder: .repository
      files.main: repository
    container:
        configuration:
          folder: .container
          files:
            main: container
            folio: folio
        folios.folder: folios
        derivatives:
          folder: derivatives
          format: jpg
          quality:
            thumbnail.folder: thumbnail
            detail.folder: detail
            best.folder: best
  data:
    folder: ${user.home}/ocr4all/data
    configuration:
      folder: .data
      files.main: data
    collection:
        configuration:
          folder: .collection
          files:
            main: collection
            sets: sets
  assemble:
    folder: ${user.home}/ocr4all/assemble
    configuration:
      folder: .assemble
      files.main: assemble
    model:
        configuration:
          folder: .model
          files:
            main: model
            engine: engine
  workspace:
    folder: ${user.home}/ocr4all/workspace
    configuration:
      folder: .ocr4all
      files:
        main: ocr4all
        user: user
        group: group
        password: password
        provider: service-provider
    models:
      folder: models
      model:
        configuration:
          folder: .model
          files:
            main: model
            assembly: assembly
        file: model
    workflows:
      folder: workflows
      file.extension: .wf
    projects:
      folder: projects
      project:
        configuration:
          folder: .project
          files:
            main: project
            folio: folio
            history: history
        images:
          folder: images
          folios.folder: folios
          derivatives:
            folder: derivatives
            format: jpg
            quality:
              thumbnail.folder: thumbnail
              detail.folder: detail
              best.folder: best
        models:
          folder: models
          configuration:
            folder: .models
            files.security: security
          model:
            configuration:
              folder: .model
              files:
                main: model
                assembly: assembly
            file: model
        sandboxes:
          folder: sandboxes
          sandbox:
            configuration:
              folder: .sandbox
              files:
                main: sandbox
                history: history
            mets:
              file: mets.xml
              group: ocr4all
            snapshots:
              folder: snapshots
              snapshot:
                configuration:
                  folder: .snapshot
                  files:
                    main: snapshot
                    process: process
                sandbox:
                  folder: sandbox
                derived.folder: derived
  opt.folder: ${user.home}/ocr4all/opt
  temporary:
    folder: ${user.home}/ocr4all/tmp
    prefix: ocr4all-
  api:
    jwt:
      issuer: ocr4all.org
      validity: 604800000
    documentation:
      source: de.uniwuerzburg.zpd.ocr4all.application.api
      title: OCR4all RESTful web API
      description: This is the official RESTful web API for OCR4all, a software for digitization of primarily very early printed documents
      version: 1.0
      contact:
        name: ocr4all
        email: ocr4all@uni-wuerzburg.de
      license: MIT License
      url:
        tos: https://www.uni-wuerzburg.de/en/sonstiges/imprint-privacy-policy
        contact: http://www.ocr4all.org
        license: https://opensource.org/licenses/MIT

#
# logging configuration: console / level info
#
logging:
  file:
    path:
    name:
  level:
    root: INFO

---
spring:
    config.activate.on-profile: logging-file

logging:
  file:
    path: /var/log/ocr4all
    name: ocr4all.log

---
spring:
    config.activate.on-profile: logging-debug

server.error.include-stacktrace: always
  
logging.level:
  "[org.springframework.security]": INFO
  "[de.uniwuerzburg.zpd.ocr4all.application]": DEBUG

---
spring:
    config.activate.on-profile: docker

server:
  port: 8080

ocr4all:
  application:
    spi.msa:
      - id: ocrd
        url: msa-ocrd:8080
        websocket:
          end-point: /event
          topic: /topic/spi
          resilience:
            max-attempts: 3
            delay-between-attempts: 1000
            wait-duration: 15000
  exchange.folder: /srv/ocr4all/exchange
  repository.folder: /srv/ocr4all/repository
  data.folder: /srv/ocr4all/data
  assemble.folder: /srv/ocr4all/assemble
  workspace.folder: /srv/ocr4all/workspace
  opt.folder: /srv/ocr4all/opt
  temporary.folder: /srv/ocr4all/tmp

---
spring:
    config.activate.on-profile: desktop
    security.user.password: no-password-required

ocr4all:
  exchange.folder: ${user.home}/ocr4all/exchange
  repository.folder: ${user.home}/ocr4all/repository
  data.folder: ${user.home}/ocr4all/data
  assemble.folder: ${user.home}/ocr4all/assemble
  workspace.folder: ${user.home}/ocr4all/workspace
  opt.folder: ${user.home}/ocr4all/opt
  temporary.folder: ${user.home}/ocr4all/tmp

---
spring:
    config.activate.on-profile: server

ocr4all:
  exchange.folder: /srv/ocr4all/exchange
  repository.folder: /srv/ocr4all/repository
  data.folder: /srv/ocr4all/data
  assemble.folder: /srv/ocr4all/assemble
  workspace.folder: /srv/ocr4all/workspace
  opt.folder: /srv/ocr4all/opt
  temporary.folder: /srv/ocr4all/tmp

---
spring:
    config.activate.on-profile: development

server:
  port: 9090

ocr4all:
  application.security.administrator.create: true
  exchange.folder: ${user.home}/ocr4all/dev/exchange
  repository.folder: ${user.home}/ocr4all/dev/repository
  data.folder: ${user.home}/ocr4all/dev/data
  assemble.folder: ${user.home}/ocr4all/dev/assemble
  workspace.folder: ${user.home}/ocr4all/dev/workspace
  opt.folder: ${user.home}/ocr4all/dev/opt
  temporary.folder: ${user.home}/ocr4all/dev/tmp
